// DestinyPlanner — 27 citations (25 Myles Munroe + 2 externes)
// step_affinity : tableau des étapes concernées (vide = universel)

import type { Quote } from '../types'

export const QUOTES: Quote[] = [
  // ── Vision (étape 1) ─────────────────────────────────────────
  {
    id: 'q-001',
    text: 'Votre rêve n\'est qu\'un rêve tant qu\'il n\'a pas de projet.',
    author: 'Myles Munroe',
    theme: 'planification',
    step_affinity: [1],
    tone: 'vision',
  },
  {
    id: 'q-002',
    text: 'La vision est la capacité de voir au-delà de votre environnement actuel, au-delà de ce qui est visible, vers ce qui est possible.',
    author: 'Myles Munroe',
    theme: 'vision',
    step_affinity: [1],
    tone: 'vision',
  },
  {
    id: 'q-003',
    text: 'Le plus grand tragédie dans la vie n\'est pas la mort, mais une vie sans but.',
    author: 'Myles Munroe',
    theme: 'but',
    step_affinity: [1],
    tone: 'faith',
  },
  {
    id: 'q-004',
    text: 'Si le but est inconnu, l\'abus est inévitable.',
    author: 'Myles Munroe',
    theme: 'but',
    step_affinity: [1],
    tone: 'vision',
  },
  {
    id: 'q-005',
    text: 'Ne passez pas votre vie à essayer d\'être quelqu\'un d\'autre. Découvrez qui vous êtes et soyez-le.',
    author: 'Myles Munroe',
    theme: 'identité',
    step_affinity: [1],
    tone: 'faith',
  },
  // ── S\'arrêter / Réflexion (étape 2) ─────────────────────────
  {
    id: 'q-006',
    text: 'Planifier demande plus de travail que travailler lui-même.',
    author: 'Myles Munroe',
    theme: 'planification',
    step_affinity: [2, 5],
    tone: 'slow-down',
  },
  {
    id: 'q-007',
    text: 'La plupart des gens courent vers leur tombeau sans avoir jamais découvert pourquoi ils sont nés.',
    author: 'Myles Munroe',
    theme: 'but',
    step_affinity: [2],
    tone: 'slow-down',
  },
  {
    id: 'q-008',
    text: 'La richesse la plus grande du monde se trouve dans les cimetières — des rêves non réalisés, des inventions jamais dévoilées, des livres jamais écrits.',
    author: 'Myles Munroe',
    theme: 'potentiel',
    step_affinity: [2],
    tone: 'vision',
  },
  {
    id: 'q-009',
    text: 'Une conviction sans action est de la superstition. Une action sans conviction est du chaos.',
    author: 'Myles Munroe',
    theme: 'conviction',
    step_affinity: [2, 7],
    tone: 'discipline',
  },
  // ── Estimer / SWOT (étape 3) ──────────────────────────────────
  {
    id: 'q-010',
    text: 'Connaître vos faiblesses n\'est pas un signe de faiblesse — c\'est le commencement de la sagesse.',
    author: 'Myles Munroe',
    theme: 'discernement',
    step_affinity: [3],
    tone: 'discipline',
  },
  {
    id: 'q-011',
    text: 'Votre plus grand ennemi n\'est pas votre circonstance extérieure, mais votre dialogue intérieur.',
    author: 'Myles Munroe',
    theme: 'mindset',
    step_affinity: [3],
    tone: 'courage',
  },
  // ── Compter le coût (étape 4) ─────────────────────────────────
  {
    id: 'q-012',
    text: 'Tout ce qui a de la valeur coûte quelque chose. Si c\'est gratuit, méfiez-vous.',
    author: 'Myles Munroe',
    theme: 'coût',
    step_affinity: [4],
    tone: 'discipline',
  },
  {
    id: 'q-013',
    text: 'Le succès n\'est pas un accident. C\'est travail acharné, persévérance, apprentissage, sacrifice et surtout amour de ce que vous faites.',
    author: 'Myles Munroe',
    theme: 'coût',
    step_affinity: [4],
    tone: 'discipline',
  },
  {
    id: 'q-014',
    text: 'La qualité de votre engagement détermine la qualité de votre résultat.',
    author: 'Myles Munroe',
    theme: 'engagement',
    step_affinity: [4, 7],
    tone: 'discipline',
  },
  {
    id: 'q-015',
    text: 'Vous ne pouvez pas payer le prix de la médiocrité — il coûte en réalité plus cher que l\'excellence.',
    author: 'Myles Munroe',
    theme: 'excellence',
    step_affinity: [4],
    tone: 'courage',
  },
  // ── Calculer / Jalons (étape 5) ───────────────────────────────
  {
    id: 'q-016',
    text: 'Un objectif sans date limite n\'est qu\'un souhait.',
    author: 'Myles Munroe',
    theme: 'planification',
    step_affinity: [5],
    tone: 'discipline',
  },
  {
    id: 'q-017',
    text: 'Ne pensez pas aux grandes réalisations — pensez aux petits pas quotidiens qui mènent aux grandes réalisations.',
    author: 'Myles Munroe',
    theme: 'progression',
    step_affinity: [5],
    tone: 'perseverance',
  },
  // ── Vérifier les ressources (étape 6) ─────────────────────────
  {
    id: 'q-018',
    text: 'La collaboration est la signature de la grande entreprise. Personne ne bâtit seul.',
    author: 'Myles Munroe',
    theme: 'ressources',
    step_affinity: [6],
    tone: 'vision',
  },
  {
    id: 'q-019',
    text: 'Ce que vous n\'avez pas aujourd\'hui ne définit pas ce que vous ne pourrez jamais avoir.',
    author: 'Myles Munroe',
    theme: 'ressources',
    step_affinity: [6],
    tone: 'faith',
  },
  // ── S\'engager (étape 7) ──────────────────────────────────────
  {
    id: 'q-020',
    text: 'Le jour où vous brûlez vos bateaux, vous découvrez des ressources insoupçonnées.',
    author: 'Myles Munroe',
    theme: 'engagement',
    step_affinity: [7],
    tone: 'courage',
  },
  {
    id: 'q-021',
    text: 'L\'engagement est la décision de ne plus décider.',
    author: 'Myles Munroe',
    theme: 'engagement',
    step_affinity: [7],
    tone: 'discipline',
  },
  // ── Persévérance / Détours ────────────────────────────────────
  {
    id: 'q-022',
    text: 'L\'échec n\'est pas l\'opposé du succès — c\'est une partie du succès.',
    author: 'Myles Munroe',
    theme: 'détour',
    step_affinity: [],
    tone: 'perseverance',
  },
  {
    id: 'q-023',
    text: 'Votre histoire n\'est pas terminée. Le dernier chapitre n\'est pas encore écrit.',
    author: 'Myles Munroe',
    theme: 'persévérance',
    step_affinity: [],
    tone: 'faith',
  },
  {
    id: 'q-024',
    text: 'Les personnes de caractère ne changent pas quand les circonstances changent.',
    author: 'Myles Munroe',
    theme: 'caractère',
    step_affinity: [],
    tone: 'perseverance',
  },
  {
    id: 'q-025',
    text: 'Le potentiel non utilisé devient une douleur. Trouvez votre but et utilisez-le.',
    author: 'Myles Munroe',
    theme: 'potentiel',
    step_affinity: [],
    tone: 'vision',
  },
  // ── Citations externes (2) ────────────────────────────────────
  {
    id: 'q-026',
    text: 'Une préparation sérieuse est déjà la moitié de la victoire.',
    author: 'Abraham Lincoln',
    theme: 'planification',
    step_affinity: [5, 6],
    tone: 'discipline',
  },
  {
    id: 'q-027',
    text: 'Ce n\'est pas la montagne que nous gravissons qui nous épuise, c\'est le caillou dans notre chaussure.',
    author: 'Muhammad Ali',
    theme: 'détour',
    step_affinity: [],
    tone: 'perseverance',
  },
]
